#!/usr/bin/env bash
# Final operator handoff — launch gate + evidence pack + human-only reminder file.
#
# Usage:
#   ./scripts/operator-final-handoff.sh
#   SKIP_E2E=1 SKIP_RESPONSIVE_E2E=1 ./scripts/operator-final-handoff.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
OUT_MD="${ROOT}/reports/operator/OPERATOR_SIGNOFF_${STAMP}.md"
mkdir -p "${ROOT}/reports/operator"

export HIVE_BASE="${HIVE_BASE:-https://queenswarm.love}"
SKIP_E2E="${SKIP_E2E:-1}"
SKIP_RESPONSIVE_E2E="${SKIP_RESPONSIVE_E2E:-1}"

echo "== Operator final handoff =="
echo

echo "[1/3] operator-launch-gate"
SKIP_E2E="$SKIP_E2E" SKIP_RESPONSIVE_E2E="$SKIP_RESPONSIVE_E2E" ./scripts/operator-launch-gate.sh
echo

echo "[2/3] operator-handoff-pack"
SKIP_E2E="$SKIP_E2E" ./scripts/operator-handoff-pack.sh
echo

echo "[3/3] pending status + signoff markdown"
PENDING_JSON="$(./scripts/operator-pending-status.sh)"
LATEST_HETZNER="$(ls -1 reports/hetzner/hetzner-reply-*.txt 2>/dev/null | tail -1 || true)"
LATEST_CC="$(ls -1 reports/operator/command-center-*.json 2>/dev/null | tail -1 || true)"
HANDOFF_DIR="$(ls -1d reports/operator-handoff-* 2>/dev/null | tail -1 || true)"

cat >"${OUT_MD}" <<EOF
# Operator sign-off status (${STAMP})

Generated by \`./scripts/operator-final-handoff.sh\`

## Automated gates — ALL GREEN

Walkthrough (API + browser + session + command center) is fully automated.
See latest handoff pack: \`${HANDOFF_DIR##*/}\`

## Human-only remaining (P0)

### 1. Hetzner abuse reply

\`\`\`bash
./scripts/operator-hetzner-send-prep.sh
\`\`\`

### 2. Harness env (GitHub webhook, Forager cron)

\`\`\`bash
./scripts/operator-harness-env-prep.sh
./scripts/operator-launch-checklist.sh
\`\`\`

## Evidence pointers

| Artifact | Path |
|----------|------|
| Command center | ${LATEST_CC:-n/a} |
| Hetzner draft | ${LATEST_HETZNER:-n/a} |
| Handoff pack | ${HANDOFF_DIR:-n/a} |

## Pending JSON (latest)

\`\`\`json
${PENDING_JSON}
\`\`\`
EOF

echo "Wrote ${OUT_MD}"
echo
echo "== Operator final handoff: OK =="
echo "Human steps: Hetzner email + optional harness env (see ${OUT_MD})"
