"""Generate HIVE.md context documents from sub-swarm state or recipe metadata."""

from __future__ import annotations

import json
from datetime import UTC, datetime
from typing import Any

from app.infrastructure.persistence.models.recipe import Recipe
from app.infrastructure.persistence.models.swarm import SubSwarm


def _memory_lines(local_memory: dict[str, Any]) -> list[str]:
    """Render structured local memory into markdown bullets."""

    lines: list[str] = []
    for key in ("goals", "rules", "constraints", "memory_summary"):
        raw = local_memory.get(key)
        if isinstance(raw, list):
            for item in raw:
                if str(item).strip():
                    lines.append(f"- {item}")
        elif isinstance(raw, str) and raw.strip():
            lines.append(f"- {raw.strip()}")
    if not lines:
        for key, value in sorted(local_memory.items()):
            if key.startswith("_"):
                continue
            if isinstance(value, (str, int, float, bool)):
                lines.append(f"- **{key}**: {value}")
            elif isinstance(value, list) and value:
                preview = ", ".join(str(v) for v in value[:6])
                lines.append(f"- **{key}**: {preview}")
    return lines


def generate_swarm_hive_md(swarm: SubSwarm) -> str:
    """Build HIVE.md for a sub-swarm colony from persisted local memory.

    Args:
        swarm: Loaded ``SubSwarm`` ORM row.

    Returns:
        UTF-8 Markdown document suitable for export or supervisor context.
    """

    memory = dict(swarm.local_memory or {})
    goals = memory.get("goals")
    rules = memory.get("rules")
    goal_block = ""
    if isinstance(goals, list) and goals:
        goal_block = "\n".join(f"- {g}" for g in goals if str(g).strip())
    elif isinstance(goals, str) and goals.strip():
        goal_block = f"- {goals.strip()}"
    else:
        goal_block = f"- Operate the **{swarm.name}** colony ({swarm.purpose.value})."

    rule_block = ""
    if isinstance(rules, list) and rules:
        rule_block = "\n".join(f"- {r}" for r in rules if str(r).strip())
    elif isinstance(rules, str) and rules.strip():
        rule_block = f"- {rules.strip()}"
    else:
        rule_block = (
            "- Only verified (simulated) outcomes reach operators.\n"
            "- Respect CostGovernor budgets and hive guardrails.\n"
            "- Sync to global hive mind on cadence."
        )

    memory_lines = _memory_lines(memory)
    memory_block = "\n".join(memory_lines) if memory_lines else "- (empty — seed goals/rules in swarm local_memory)"

    sync_at = swarm.last_global_sync_at
    sync_label = sync_at.isoformat() if sync_at is not None else "never"

    return f"""# HIVE — {swarm.name}

> Auto-generated by Queenswarm · {datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M UTC")}

## Purpose

`{swarm.purpose.value}` · members={swarm.member_count} · pollen={swarm.total_pollen:.1f}

## Goals

{goal_block}

## Rules

{rule_block}

## Memory summary

{memory_block}

## Sync telemetry

- Last global sync: `{sync_label}`
- Active: `{swarm.is_active}`
- Colony id: `{swarm.id}`
"""


def generate_recipe_hive_md(recipe: Recipe) -> str:
    """Build companion HIVE.md for a recipe skill export bundle.

    Args:
        recipe: Recipe Library row including workflow template JSON.

    Returns:
        Markdown hive context describing verification signals and workflow memory.
    """

    total = recipe.success_count + recipe.fail_count
    success_rate = float(recipe.success_count / total) if total else 0.0
    verified_label = recipe.verified_at.isoformat() if recipe.verified_at else "not verified"
    steps = _workflow_step_labels(recipe.workflow_template)

    steps_block = "\n".join(f"- {label}" for label in steps) if steps else "- (no structured steps in workflow_template)"

    return f"""# HIVE — {recipe.name}

> Recipe Library export · Queenswarm verified workflow context

## Goals

- Reproduce the verified workflow: **{recipe.name}**
- {(recipe.description or "No description on catalog row.").strip()}

## Rules

- Run simulation audit before treating outputs as verified.
- Honor guardrails embedded in workflow steps.
- Award pollen only after threshold-backed verification passes.

## Verification signals

- Verified at: `{verified_label}`
- Success rate: `{success_rate:.0%}` ({recipe.success_count} wins / {recipe.fail_count} fails)
- Avg pollen: `{recipe.avg_pollen_earned:.1f}`
- Tags: {", ".join(recipe.topic_tags or []) or "(none)"}

## Workflow memory

{steps_block}

## Recipe id

`{recipe.id}`
"""


def _workflow_step_labels(template: dict[str, Any]) -> list[str]:
    """Extract human-readable step labels from a workflow template blob."""

    steps_raw = template.get("steps")
    if not isinstance(steps_raw, list):
        return []
    labels: list[str] = []
    for idx, step in enumerate(steps_raw, start=1):
        if not isinstance(step, dict):
            continue
        label = (
            str(step.get("description") or "").strip()
            or str(step.get("title") or "").strip()
            or str(step.get("name") or "").strip()
            or f"Step {idx}"
        )
        role = str(step.get("agent_role") or step.get("role") or "").strip()
        if role:
            labels.append(f"{label} (`{role}`)")
        else:
            labels.append(label)
    return labels


def meta_json_preview(recipe: Recipe) -> dict[str, Any]:
    """Serialize export metadata for ``meta.json`` in skill bundles."""

    total = recipe.success_count + recipe.fail_count
    success_rate = float(recipe.success_count / total) if total else 0.0
    return {
        "source": "queenswarm.love",
        "recipe_id": str(recipe.id),
        "recipe_name": recipe.name,
        "verified": recipe.verified_at is not None,
        "verified_at": recipe.verified_at.isoformat() if recipe.verified_at else None,
        "success_rate": round(success_rate, 4),
        "avg_pollen_earned": recipe.avg_pollen_earned,
        "topic_tags": list(recipe.topic_tags or []),
        "export_version": "1.0.0",
    }


__all__ = ["generate_recipe_hive_md", "generate_swarm_hive_md", "meta_json_preview"]
