/** Routes prefetched after idle — warms JS chunks for common operator navigation. */
export const HIVE_IDLE_PREFETCH_ROUTES: readonly string[] = [
  "/cockpit",
  "/oracle",
  "/agents",
  "/tasks",
  "/swarms",
  "/integrations",
  "/ballroom",
  "/workflows",
  "/knowledge",
  "/foragers",
  "/monitoring",
  "/jobs",
  "/simulations",
  "/recipes",
  "/external-projects",
  "/plugins",
  "/design-system",
  /* Settings hub — warm all tabs so section switches feel like dashboard layout modal */
  "/settings",
  "/settings/security",
  "/settings/costs",
  "/settings/audit",
  "/settings/llm-keys",
  "/settings/platform",
  "/settings/harness",
  "/settings/accounts",
  "/settings/command-center",
  "/settings/capabilities",
  "/settings/api-keys",
  "/settings/billing",
  "/settings/enterprise",
  "/settings/sharing",
  "/settings/team",
  "/settings/notifications",
];
