/** Deep links from Manual → live app surfaces (settings, agents, integrations, …). */

import { cockpitSectionHref } from "@/lib/cockpit-routes";
import { executionStudioSectionHref } from "@/lib/integrations-routes";
import { knowledgeTabHref } from "@/lib/knowledge-routes";

/** Stable hrefs referenced from manual copy and function guide cards. */
export const MANUAL_HREFS = {
  agenticOs: "/agentic-os",
  agenticOsLanes: cockpitSectionHref("lanes"),
  agenticOsInnovation: cockpitSectionHref("innovation"),
  agenticOsCommand: cockpitSectionHref("command"),
  agents: "/agents",
  agentsSessions: "/agents#sessions",
  ballroom: "/ballroom",
  foragers: "/foragers",
  integrations: "/integrations",
  integrationsHub: "/integrations?tab=hub",
  integrationsMarketplace: "/integrations?tab=marketplace",
  integrationsStudio: "/integrations?tab=studio",
  integrationsStudioLanes: executionStudioSectionHref("lanes", "codebase-pending"),
  integrationsStudioInnovation: executionStudioSectionHref("innovation", "innovation-lab"),
  integrationsStudioNotifications: executionStudioSectionHref("analytics"),
  knowledge: "/knowledge",
  knowledgeCurated: knowledgeTabHref("memory"),
  knowledgeDreaming: knowledgeTabHref("dreaming"),
  knowledgeOutputs: knowledgeTabHref("outputs"),
  knowledgeRecipes: knowledgeTabHref("recipes"),
  knowledgeWiki: knowledgeTabHref("wiki"),
  knowledgeGoals: knowledgeTabHref("goals"),
  login: "/login",
  manualCanonical: "/manual#canonical-workflow",
  manualSetup: "/manual#setup-once",
  manualWikiLayer: "/manual#wiki-layer",
  manualIngestRouter: "/manual#ingest-router",
  manualSkillHotTier: "/manual#skill-hot-tier",
  manualLeadGenLane: "/manual#lead-gen-lane",
  manualPatternRouter: "/manual#pattern-router",
  manualAutomationLadder: "/manual#automation-ladder",
  manualAgentWorkflows: "/manual#agent-workflows",
  manualHarnessFourCs: "/manual#harness-four-cs",
  manualInnovationViability: "/manual#innovation-viability",
  manualMaintainerSafety: "/manual#maintainer-safety",
  agentsLeadGenLane: "/agents?preset=lead-gen-lane",
  knowledgeIngest: "/knowledge#ingest",
  settingsHarness: "/settings/harness",
  settingsLlmKeys: "/settings/llm-keys",
  settingsApiKeys: "/settings/api-keys",
  settingsNotifications: "/settings/notifications",
  settingsSecurity: "/settings/security",
  swarms: "/swarms",
  tasks: "/tasks",
  tasksNew: "/tasks/new",
  skillFactory: "/apps-tools/skill-factory",
  manualSkillFactory: "/manual#skill-factory",
  contentPackFactory: "/apps-tools/content-factory#pipeline",
  manualContentPackFactory: "/manual#content-pack-factory",
} as const;

/** Per function-guide card id → open-in-app href. */
export const MANUAL_FUNCTION_HREFS: Record<string, string> = {
  "canonical-session": MANUAL_HREFS.agentsSessions,
  "canonical-knowledge": MANUAL_HREFS.knowledgeCurated,
  "canonical-tasks": MANUAL_HREFS.tasks,
  "cockpit-home": MANUAL_HREFS.agenticOs,
  "dashboard-overview": MANUAL_HREFS.agenticOs,
  "dashboard-monitoring": "/monitoring",
  "agents-session": MANUAL_HREFS.agentsSessions,
  "agents-spawn": "/agents/new",
  "agents-foragers": MANUAL_HREFS.foragers,
  "tasks-new": MANUAL_HREFS.tasksNew,
  "tasks-routines": MANUAL_HREFS.tasks,
  "knowledge-hivemind": MANUAL_HREFS.knowledge,
  "knowledge-outputs": MANUAL_HREFS.knowledgeOutputs,
  "knowledge-dreaming": MANUAL_HREFS.knowledgeDreaming,
  "knowledge-wiki": MANUAL_HREFS.knowledgeWiki,
  "knowledge-wiki-gardener": MANUAL_HREFS.knowledgeWiki,
  "knowledge-wiki-obsidian": MANUAL_HREFS.knowledgeWiki,
  "knowledge-ingest": MANUAL_HREFS.knowledgeIngest,
  "knowledge-youtube-ingest": MANUAL_HREFS.knowledgeIngest,
  "knowledge-skill-hot-tier": MANUAL_HREFS.manualSkillHotTier,
  "lead-gen-lane": MANUAL_HREFS.agentsLeadGenLane,
  "pattern-router": MANUAL_HREFS.manualPatternRouter,
  "automation-ladder": MANUAL_HREFS.manualAutomationLadder,
  "agent-workflows": MANUAL_HREFS.manualAgentWorkflows,
  "tasks-mission-kanban": MANUAL_HREFS.manualAgentWorkflows,
  "integrations-connectors": MANUAL_HREFS.integrationsHub,
  "integrations-marketplace": MANUAL_HREFS.integrationsMarketplace,
  "cockpit-four-lanes": MANUAL_HREFS.agenticOsLanes,
  "cockpit-digest-inbox": MANUAL_HREFS.agenticOsLanes,
  "cockpit-overview": MANUAL_HREFS.agenticOs,
  "cockpit-command": MANUAL_HREFS.agenticOsCommand,
  "bee-hotline": MANUAL_HREFS.agenticOsCommand,
  "intent-crystallizer": MANUAL_HREFS.agenticOsCommand,
  "zero-ui-hive": MANUAL_HREFS.settingsNotifications,
  "icm-tools": MANUAL_HREFS.agenticOsCommand,
  "swarm-fleet": cockpitSectionHref("fleet"),
  "cockpit-modules": cockpitSectionHref("modules"),
  "innovation-lab": MANUAL_HREFS.manualInnovationViability,
  "harness-four-cs": MANUAL_HREFS.manualHarnessFourCs,
  "innovation-viability": MANUAL_HREFS.manualInnovationViability,
  "maintainer-safety": MANUAL_HREFS.manualMaintainerSafety,
  "ballroom-realtime": MANUAL_HREFS.ballroom,
  "settings-security": MANUAL_HREFS.settingsSecurity,
  "settings-team": "/settings/team",
  "settings-billing": "/settings/costs",
  "settings-voice-providers": MANUAL_HREFS.settingsLlmKeys,
  "content-pack-factory": MANUAL_HREFS.contentPackFactory,
};
